import Head from 'next/head'
import Image from 'next/image'
import { useState,useEffect } from 'react';
import styles from '../styles/Home.module.css'
import { Calendar, utils } from "react-modern-calendar-datepicker";
import "react-modern-calendar-datepicker/lib/DatePicker.css";
import moment from "moment";
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';
export default function Home() {


  const [selectedDate, setSelectedDate] = useState({
    year: moment().year(),
    month: moment().month() + 1,
    day: moment().date(),
  });

  var date = new Date();

  // let minimumDate = date.getDate() + 3;
   const max = moment().add(12, 'days').toDate();
  // minimumDate.setDate(minimumDate.getDate() + 1);
  // let maxDate = new Date(
  //   minimumDate.getFullYear(),
  //   minimumDate.getMonth() + 1,
  //   0
  // );




  const disabledTimes = [];

  const [disabledDays, setDisabledDays] = useState([]);

  const [unavailableTimes, setUnavailableTimes] = useState([]);





  const handleCalendar = (e) => {
    setSelectedDate(e);
    console.log(e);  // handle selected date
    setDisabledDays([...disabledDays, e]);

  };





  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
 <div>
    hello man


    <div className='flex flex-col'>
            <Calendar
              onChange={handleCalendar}
              calendarClassName='border-2 border-pink-200 h-[100% dark:border-neutral-900'
              colorPrimary='#f8a4d1'
              value={selectedDate}
              minimumDate={utils().getToday()  }
              maximumDate= { max }
           
              disabledDays={disabledDays}
            />
            </div>


            <Stack spacing={2} direction="row">
      <Button variant="text">Text</Button>
      <Button variant="contained">Contained</Button>
      <Button variant="outlined">Outlined</Button>
    </Stack>

 </div>


    </div>
  )
}
