import React from "react";
import Head from "next/head";
import L from "leaflet";
import styles from '../../styles/villa.module.css';
import Script from "next/script";
import { useState, useEffect, useRef } from "react";

import { MapContainer, TileLayer, useMap, Marker, Popup } from "react-leaflet";
const markericon =
  "https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon.png";

const Villamap = ({ image, lat, lng }) => {
  console.log("coordinate issss- :--------->⏩", lat, lng);

  const position = [40.766666, 29.916668];
  const pos2 = [Number(lat), Number(lng)];

  console.log("position1 issss- :--------->⏩", pos2, "---...", position);

  const markerRef = useRef();

  const changeMarkerPos = (e) => {
    console.log("changeMarkerPos----->", markerRef.current._latlng);
  };

  const pinMB = L.icon({
    iconUrl: markericon,
    iconSize: [24, 41],
    iconAnchor: [0, 44],
    popupAnchor: [12, -40],
    shadowUrl: null,
    shadowSize: null,
    shadowAnchor: null,
  });

  return (
    <div>
      <div>
        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

            <link
              rel="stylesheet"
              href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
              integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
              crossOrigin=""
            />
          </Head>

          <>
            <Script
              src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
              integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
              crossOrigin=""
            ></Script>
          </>
        </div>
      </div>

      {/* -inf- */}

      <div>{}</div>

      <div>
        <div>
          <MapContainer
          className={styles.map}
            // center={position}
            center={position}
            zoom={13}
            scrollWheelZoom={false}
          >
            <TileLayer
              attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
            <Marker
              icon={pinMB}
            //   draggable={true}
              onDragend={changeMarkerPos}
              ref={markerRef}
              position={pos2}

              //  position={position}
            >
              <Popup>
                <p className="popup">villa image</p>
                <img
                  className="popup-img   w-[77px]  h-[77px]"
                  src={image}
                  alt="Sacré-Coeur"
                />
              </Popup>
            </Marker>
          </MapContainer>
        </div>
      </div>
      {/* <h1 onClick={changeMarkerPos}>change maps</h1> */}
    </div>
  );
};

export default Villamap;
